import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useContractWrite, useWaitForTransaction } from "wagmi";
import { useCounterGetNumber, usePrepareCounterSetNumber } from "wagmi-config";

const Home: NextPage = () => {
  const [number, setNumber] = useState<bigint>(BigInt(0));

  const { data: numberFetched } = useCounterGetNumber({});

  const { config } = usePrepareCounterSetNumber({
    args: [number],
  });

  const { data, write } = useContractWrite({ ...config });

  // const { isSuccess: txDone } = useWaitForTransaction({
  //   hash: data?.hash,
  // });

  return (
    <div className="h-full flex border flex-col justify-center items-center">
      <Head>
        <title>Typescript Eth Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="border-red-500">
        <label className="label">Number</label>
        <input
          className="input input-bordered"
          type="number"
          placeholder="Set new number..."
          onChange={(e) => {
            setNumber(BigInt(e.target.value));
          }}
        />
        <button
          className="btn btn-primary"
          onClick={() => {
            write && write();
          }}
        >
          SET
        </button>
        <div>Current number: {numberFetched?.toString()}</div>
      </div>
    </div>
  );
};

export default Home;
