/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Greeter } from "./Greeter";
export type { Multicall } from "./Multicall";

export { Greeter__factory } from "./factories/Greeter__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
